# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=6.0.0+1.21.1
group=com.illusivesoulworks.shulkerboxslot
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Shulker Box Slot
mod_author=Illusive Soulworks
mod_id=shulkerboxslot
license=LGPL-3.0-or-later
issues_url=https://github.com/illusivesoulworks/shulkerboxslot/issues
sources_url=https://github.com/illusivesoulworks/shulkerboxslot
description=Adds accessory support for Shulker Boxes for easier access and management.
minecraft_version_range=[1.21, 1.22)
minecraft_version_range_alt=~1.21

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430

# SpectreLib
spectrelib_version=0.17.2+1.21

# Parchment
parchment_mc=1.21
parchment_version=2024.07.28

# Fabric
fabric_version=0.104.0+1.21.1
fabric_loader_version=0.16.5
trinkets_version=3.10.0
cca_version=6.1.0
mod_menu_version=11.0.1

# NeoForge
neoforge_version=21.1.1
neoforge_version_range=[21.0.143,)
curios_version=9.0.6+1.21
curios_version_range=[7.0.0,)

# Publishing Options
cf_id=316881
cf_page=https://www.curseforge.com/minecraft/mc-mods/shulker-box-slot
modrinth_id=R5T1RmWr
modrinth_page=https://modrinth.com/mod/shulker-box-slot
release_type=release
release_versions=1.21.1,1.21
changelog_link=https://github.com/illusivesoulworks/shulkerboxslot/blob/1.21.x/CHANGELOG.md

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
